// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetDashboard():Promise<main.DashboardData>;

export function GetHourlyActivity():Promise<Array<main.HourlyBucket>>;

export function AuthorizeSession(sessionID:string):Promise<boolean>;

export function DeauthorizeSession(sessionID:string):Promise<boolean>;

export function DisconnectUnauthorized():Promise<number>;
